// Cloudflare Worker: Claude relay for the website's "Explain more" and "+5 new" buttons.
//
// - Callers must be signed in to your site (Firebase ID token).
// - Each person saves their OWN Claude (Anthropic) API key to their account once (PUT /key). The relay
//   encrypts it (AES-GCM, secret KEY_ENCRYPTION_SECRET) and stores it in Firestore under apikeys/<uid>,
//   which no browser can read (firestore.rules). It is decrypted only here, per request, and never
//   returned to any browser or logged. DELETE /key wipes it.
// - Every prompt is built here, so this can't be used as a general-purpose chatbot.
// - Questions generated here are written to Firestore by THIS Worker with a service account, straight from
//   Claude's response. Browsers can't write to the shared pool (see firestore.rules).
// - POST /submit adds questions made in the Claude version (claude.ai) to the shared pool. Those come through
//   the person's browser, so they're only format-checked, de-duplicated, and capped per person per day.
import Anthropic from "@anthropic-ai/sdk";
// Trusted course outline generated by src/build.py from the repo's question files.
// The generation prompt is built only from this, never from text the browser sends.
import TOPICS from "./topics.json" with { type: "json" };

const DEFAULT_MODEL = "claude-opus-5";

const QUESTIONS_SCHEMA = {
  type: "object",
  properties: {
    questions: {
      type: "array",
      items: {
        type: "object",
        properties: {
          stem: { type: "string" },
          correct: { type: "string" },
          wrong: { type: "array", items: { type: "string" } },
          explanation: { type: "string" }
        },
        required: ["stem", "correct", "wrong", "explanation"],
        additionalProperties: false
      }
    }
  },
  required: ["questions"],
  additionalProperties: false
};

export default {
  async fetch(request, env) {
    const origin = request.headers.get("origin") || "";
    const allowed = (env.ALLOWED_ORIGINS || "").split(",").map(s => s.trim()).filter(Boolean);
    const cors = {
      "access-control-allow-origin": allowed.includes(origin) ? origin : (allowed[0] || ""),
      "access-control-allow-methods": "GET, POST, PUT, DELETE, OPTIONS",
      "access-control-allow-headers": "content-type, authorization",
      "access-control-max-age": "86400",
      vary: "origin"
    };
    const json = (obj, status = 200) => new Response(JSON.stringify(obj), { status, headers: { ...cors, "content-type": "application/json" } });

    if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: cors });
    if (!allowed.includes(origin)) return json({ error: "Origin not allowed" }, 403);

    const kind = new URL(request.url).pathname.replace(/^\/+|\/+$/g, "");
    const route = request.method + " " + kind;
    if (!["POST explain", "POST generate", "POST submit", "GET key", "PUT key", "DELETE key"].includes(route)) return json({ error: "Unknown endpoint" }, 404);

    // 1. Signed-in users of your site only.
    const token = (request.headers.get("authorization") || "").replace(/^Bearer\s+/i, "");
    const uid = await verifyFirebaseUser(token, env);
    if (!uid) return json({ error: "sign_in", message: "Sign in required" }, 401);

    // 2. Saved-key management: status, save (verified first), wipe.
    try {
      if (route === "GET key") {
        const rec = await loadKeyRecord(env, uid);
        return json(rec ? { saved: true, hint: rec.hint, savedAt: rec.savedAt } : { saved: false });
      }
      if (route === "DELETE key") {
        await deleteKeyRecord(env, uid);
        return json({ saved: false });
      }
      if (route === "PUT key") {
        let body; try { body = await request.json(); } catch { return json({ error: "bad_input", message: "Invalid JSON" }, 400); }
        const key = String(body.key || "").trim();
        if (!/^sk-ant-[A-Za-z0-9_-]{20,200}$/.test(key)) return json({ error: "bad_key", message: "That doesn't look like a Claude API key" }, 400);
        await new Anthropic({ apiKey: key, maxRetries: 1 }).models.list({ limit: 1 });  // free check that the key works
        const hint = key.slice(0, 7) + "…" + key.slice(-4);
        const savedAt = new Date().toISOString();
        await saveKeyRecord(env, uid, { enc: await encryptKey(env, key), hint, savedAt });
        return json({ saved: true, hint, savedAt });
      }
    } catch (e) {
      if (e instanceof Anthropic.AuthenticationError || e instanceof Anthropic.PermissionDeniedError) return json({ error: "bad_key", message: "Anthropic rejected that API key" }, 400);
      if (e instanceof Anthropic.APIError) return json({ error: "claude", message: "Couldn't check the key with Anthropic. Try again." }, 502);
      return json({ error: "store", message: "Couldn't update your saved key. Try again." }, 502);
    }

    // 2b. Questions generated in the Claude version go straight into the shared pool (no API key needed).
    // They arrive through the person's browser, so the relay only checks format, removes duplicates, and caps volume.
    if (route === "POST submit") {
      let input; try { input = await request.json(); } catch { return json({ error: "bad_input", message: "Invalid JSON" }, 400); }
      try {
        const items = readSubmit(input);
        const fresh = []; let duplicates = 0;
        for (const it of items) {
          it.id = await submissionId(it);
          if (fresh.some(f => f.id === it.id) || await firestore(env, "GET", "submissions/" + it.id)) duplicates++; else fresh.push(it);
        }
        const room = Math.max(0, SUBMIT_DAILY_LIMIT - await submittedToday(env, uid));
        const take = fresh.slice(0, room), overLimit = fresh.length - take.length;
        const groups = new Map();
        for (const it of take) {
          await markSubmitted(env, it, uid);
          const k = it.courseId + "|" + it.topicCode;
          if (!groups.has(k)) groups.set(k, { course: it.courseId, topic: it.topicCode, questions: [] });
          groups.get(k).questions.push({ stem: it.stem, correct: it.correct, wrong: it.wrong, explanation: it.explanation });
        }
        const added = [];
        for (const g of groups.values()) added.push({ id: await saveCommunity(env, { ...g, uid, model: "claude-app", source: "claude-app" }), ...g });
        if (take.length) await countSubmitted(env, uid, take.length);
        return json({ added, count: take.length, duplicates, overLimit });
      } catch (e) {
        if (e instanceof BadInput) return json({ error: "bad_input", message: e.message }, 400);
        return json({ error: "store", message: "Couldn't add the questions. Try again." }, 502);
      }
    }

    // 3. Use the caller's saved key (billed to them).
    let apiKey;
    try {
      const rec = await loadKeyRecord(env, uid);
      if (!rec) return json({ error: "no_key", message: "Save your Claude API key on the Account page first" }, 400);
      apiKey = await decryptKey(env, rec.enc);
    } catch { return json({ error: "store", message: "Couldn't read your saved key. Try again." }, 502); }

    // 3. Optional per-user daily cap (protects the shared database from floods).
    if (env.USAGE) {
      const key = `${uid}:${new Date().toISOString().slice(0, 10)}`;
      const used = parseInt((await env.USAGE.get(key)) || "0", 10);
      if (used >= parseInt(env.DAILY_LIMIT || "60", 10)) return json({ error: "limit", message: "Daily limit reached" }, 429);
      await env.USAGE.put(key, String(used + 1), { expirationTtl: 172800 });
    }

    let input;
    try { input = await request.json(); } catch { return json({ error: "bad_input", message: "Invalid JSON" }, 400); }

    const client = new Anthropic({ apiKey, maxRetries: 1 });
    const model = env.CLAUDE_MODEL || DEFAULT_MODEL;

    try {
      if (kind === "explain") {
        const c = readExplain(input);
        const response = await client.beta.messages.create({
          model,
          max_tokens: 4096,
          betas: ["server-side-fallback-2026-07-01"],
          fallbacks: "default",               // if Claude declines, Anthropic retries on its recommended fallback model
          output_config: { effort: "low" },   // short explanations don't need deep reasoning
          messages: [{ role: "user", content: explainPrompt(c) }]
        });
        if (response.stop_reason === "refusal") return json({ error: "declined", message: "Claude declined this request" }, 422);
        const text = response.content.filter(b => b.type === "text").map(b => b.text).join("").trim();
        return json({ text });
      }

      const c = readGenerate(input);
      const response = await client.beta.messages.create({
        model,
        max_tokens: 8192,
        betas: ["server-side-fallback-2026-07-01"],
        fallbacks: "default",
        output_config: { format: { type: "json_schema", schema: QUESTIONS_SCHEMA } },
        messages: [{ role: "user", content: generatePrompt(c) }]
      });
      if (response.stop_reason === "refusal") return json({ error: "declined", message: "Claude declined this request" }, 422);
      const text = response.content.filter(b => b.type === "text").map(b => b.text).join("");
      const questions = (JSON.parse(text).questions || [])
        .filter(q => q && q.stem && q.correct && Array.isArray(q.wrong) && q.wrong.length >= 3)
        .slice(0, 5)
        .map(q => ({ stem: q.stem, correct: q.correct, wrong: q.wrong.slice(0, 3), explanation: q.explanation || "" }));
      if (!questions.length) return json({ error: "empty", message: "Claude returned no usable questions" }, 502);

      // Save to the shared pool directly from Claude's response.
      const id = await saveCommunity(env, { course: c.courseId, topic: c.topicCode, questions, uid, model: response.model || model });
      return json({ id, questions });
    } catch (e) {
      if (e instanceof BadInput) return json({ error: "bad_input", message: e.message }, 400);
      if (e instanceof Anthropic.AuthenticationError || e instanceof Anthropic.PermissionDeniedError) return json({ error: "bad_key", message: "Your saved API key was rejected. Replace it on the Account page." }, 400);
      if (e instanceof Anthropic.RateLimitError) return json({ error: "busy", message: "Your API key hit a rate limit" }, 429);
      if (e instanceof Anthropic.BadRequestError && /credit/i.test(e.message || "")) return json({ error: "no_credits", message: "Your Anthropic account has no credits" }, 402);
      if (e instanceof Anthropic.APIError) return json({ error: "claude", message: "Claude API error" }, 502);
      if (e instanceof StoreError) return json({ error: "store", message: "Couldn't save questions" }, 502);
      return json({ error: "server", message: "Server error" }, 500);
    }
  }
};

/* ---------- auth ---------- */

// A Firebase ID token is valid if Google's Identity Toolkit can look it up for your project.
async function verifyFirebaseUser(idToken, env) {
  if (!idToken || idToken.length > 4096 || !env.FIREBASE_API_KEY) return null;
  const r = await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${encodeURIComponent(env.FIREBASE_API_KEY)}`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({ idToken })
  });
  if (!r.ok) return null;
  const data = await r.json();
  return (data.users && data.users[0] && data.users[0].localId) || null;
}

/* ---------- Firestore write with a service account (bypasses client rules by design) ---------- */

class StoreError extends Error {}
let cachedToken = null;

async function googleAccessToken(env) {
  if (cachedToken && cachedToken.exp > Date.now() + 60000) return cachedToken.token;
  let sa;
  try { sa = JSON.parse(env.FIREBASE_SERVICE_ACCOUNT); } catch { throw new StoreError("FIREBASE_SERVICE_ACCOUNT secret is missing or not JSON"); }
  const now = Math.floor(Date.now() / 1000);
  const b64url = s => btoa(s).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
  const header = b64url(JSON.stringify({ alg: "RS256", typ: "JWT" }));
  const claims = b64url(JSON.stringify({ iss: sa.client_email, scope: "https://www.googleapis.com/auth/datastore", aud: "https://oauth2.googleapis.com/token", iat: now, exp: now + 3600 }));
  const pem = sa.private_key.replace(/-----[^-]+-----/g, "").replace(/\s+/g, "");
  const der = Uint8Array.from(atob(pem), ch => ch.charCodeAt(0));
  const key = await crypto.subtle.importKey("pkcs8", der, { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" }, false, ["sign"]);
  const sig = new Uint8Array(await crypto.subtle.sign("RSASSA-PKCS1-v1_5", key, new TextEncoder().encode(`${header}.${claims}`)));
  const jwt = `${header}.${claims}.${b64url(String.fromCharCode(...sig))}`;
  const r = await fetch("https://oauth2.googleapis.com/token", {
    method: "POST",
    headers: { "content-type": "application/x-www-form-urlencoded" },
    body: `grant_type=${encodeURIComponent("urn:ietf:params:oauth:grant-type:jwt-bearer")}&assertion=${jwt}`
  });
  if (!r.ok) throw new StoreError("Google token exchange failed");
  const t = await r.json();
  cachedToken = { token: t.access_token, exp: Date.now() + (t.expires_in || 3600) * 1000 };
  return cachedToken.token;
}

async function saveCommunity(env, rec) {
  try { return await writeCommunity(env, rec); }
  catch (e) { throw e instanceof StoreError ? e : new StoreError(String(e && e.message || e)); }  // any credential/network failure reads as "couldn't save"
}

async function writeCommunity(env, rec) {
  let project;
  try { project = JSON.parse(env.FIREBASE_SERVICE_ACCOUNT).project_id; } catch { throw new StoreError("bad service account"); }
  const token = await googleAccessToken(env);
  const r = await fetch(`https://firestore.googleapis.com/v1/projects/${project}/databases/(default)/documents/community`, {
    method: "POST",
    headers: { authorization: `Bearer ${token}`, "content-type": "application/json" },
    body: JSON.stringify({
      fields: {
        course: { stringValue: rec.course },
        topic: { stringValue: rec.topic },
        json: { stringValue: JSON.stringify(rec.questions) },
        uid: { stringValue: rec.uid },
        model: { stringValue: String(rec.model) },
        source: { stringValue: rec.source || "relay" },
        createdAt: { timestampValue: new Date().toISOString() }
      }
    })
  });
  if (!r.ok) throw new StoreError("Firestore write failed: " + r.status);
  const doc = await r.json();
  return doc.name.split("/").pop();
}

/* ---------- saved API keys: encrypted at rest, readable only by this relay ---------- */

async function aesKey(env) {
  const raw = Uint8Array.from(atob(String(env.KEY_ENCRYPTION_SECRET || "")), c => c.charCodeAt(0));
  if (raw.length !== 32) throw new StoreError("KEY_ENCRYPTION_SECRET must be 32 random bytes, base64-encoded");
  return crypto.subtle.importKey("raw", raw, "AES-GCM", false, ["encrypt", "decrypt"]);
}
const toB64 = u8 => { let s = ""; for (const b of u8) s += String.fromCharCode(b); return btoa(s); };
const fromB64 = s => Uint8Array.from(atob(s), c => c.charCodeAt(0));
async function encryptKey(env, plain) {
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const ct = new Uint8Array(await crypto.subtle.encrypt({ name: "AES-GCM", iv }, await aesKey(env), new TextEncoder().encode(plain)));
  return toB64(iv) + "." + toB64(ct);
}
async function decryptKey(env, enc) {
  const [iv, ct] = String(enc).split(".");
  const pt = await crypto.subtle.decrypt({ name: "AES-GCM", iv: fromB64(iv) }, await aesKey(env), fromB64(ct));
  return new TextDecoder().decode(pt);
}
async function firestore(env, method, path, body) {
  let project;
  try { project = JSON.parse(env.FIREBASE_SERVICE_ACCOUNT).project_id; } catch { throw new StoreError("bad service account"); }
  const token = await googleAccessToken(env);
  const r = await fetch(`https://firestore.googleapis.com/v1/projects/${project}/databases/(default)/documents/${path}`, {
    method, headers: { authorization: `Bearer ${token}`, "content-type": "application/json" }, body: body ? JSON.stringify(body) : undefined
  });
  if (r.status === 404 && method !== "PATCH") return null;
  if (!r.ok) throw new StoreError(`Firestore ${method} ${r.status}`);
  return r.status === 204 ? null : r.json();
}
const keyPath = uid => "apikeys/" + encodeURIComponent(uid);
async function loadKeyRecord(env, uid) {
  const doc = await firestore(env, "GET", keyPath(uid));
  if (!doc || !doc.fields) return null;
  const f = doc.fields;
  return { enc: f.enc.stringValue, hint: f.hint.stringValue, savedAt: f.savedAt.timestampValue };
}
function saveKeyRecord(env, uid, rec) {
  return firestore(env, "PATCH", keyPath(uid), { fields: { enc: { stringValue: rec.enc }, hint: { stringValue: rec.hint }, savedAt: { timestampValue: rec.savedAt } } });
}
function deleteKeyRecord(env, uid) { return firestore(env, "DELETE", keyPath(uid)); }

/* ---------- questions from the Claude version ---------- */

const SUBMIT_DAILY_LIMIT = 40;   // per person per day, so one account can't flood the shared pool
async function submissionId(it) {
  const norm = it.courseId + "|" + it.topicCode + "|" + it.stem.toLowerCase().replace(/\s+/g, " ").trim();
  const d = new Uint8Array(await crypto.subtle.digest("SHA-256", new TextEncoder().encode(norm)));
  return [...d.slice(0, 16)].map(b => b.toString(16).padStart(2, "0")).join("");
}
// submissions/<hash> marks a question as already added (duplicate check).
function markSubmitted(env, it, uid) {
  return firestore(env, "PATCH", "submissions/" + it.id, { fields: {
    course: { stringValue: it.courseId }, topic: { stringValue: it.topicCode }, uid: { stringValue: uid },
    status: { stringValue: "added" }, createdAt: { timestampValue: new Date().toISOString() } } });
}
const quotaPath = uid => "quota/" + encodeURIComponent(uid + "_" + new Date().toISOString().slice(0, 10));
async function submittedToday(env, uid) {
  const doc = await firestore(env, "GET", quotaPath(uid));
  return doc && doc.fields && doc.fields.n ? parseInt(doc.fields.n.integerValue, 10) || 0 : 0;
}
async function countSubmitted(env, uid, n) {
  const total = (await submittedToday(env, uid)) + n;
  return firestore(env, "PATCH", quotaPath(uid), { fields: { n: { integerValue: String(total) } } });
}
function readSubmit(b) {
  const list = Array.isArray(b.questions) ? b.questions : [];
  if (!list.length || list.length > 20) throw new BadInput("Send between 1 and 20 questions");
  return list.map(q => {
    const courseId = String(q.courseId || ""), topicCode = String(q.topicCode || "");
    if (!Object.prototype.hasOwnProperty.call(TOPICS, courseId + "|" + topicCode)) throw new BadInput("Unknown course or topic");
    const wrong = Array.isArray(q.wrong) ? q.wrong.slice(0, 3).map(w => str(w, 500)) : [];
    const it = { courseId, topicCode, stem: str(q.stem, 1500), correct: str(q.correct, 500), wrong, explanation: typeof q.explanation === "string" ? q.explanation.slice(0, 1500) : "" };
    if (wrong.length !== 3 || new Set([it.correct, ...wrong].map(x => x.trim().toLowerCase())).size !== 4) throw new BadInput("Each question needs one correct and three different wrong answers");
    return it;
  });
}
/* ---------- input validation and prompts ---------- */

class BadInput extends Error {}
const str = (v, max) => { if (typeof v !== "string" || !v.trim()) throw new BadInput("Missing field"); return v.slice(0, max); };
const idx = v => { const n = Number(v); if (!Number.isInteger(n) || n < 0 || n > 3) throw new BadInput("Bad index"); return n; };

function readExplain(b) {
  if (!Array.isArray(b.options) || b.options.length !== 4) throw new BadInput("Need four options");
  return {
    course: str(b.course, 80), topicCode: str(b.topicCode, 10), topicName: str(b.topicName, 120),
    stem: str(b.stem, 1500), options: b.options.map(o => str(o, 500)),
    correct: idx(b.correct), picked: idx(b.picked),
    fig: typeof b.fig === "string" ? b.fig.slice(0, 3000) : ""
  };
}
// Only the course id and topic code are taken from the request; everything that goes into the prompt
// comes from TOPICS, so a user can't slip their own text (or their own questions) into the shared pool.
function readGenerate(b) {
  const courseId = String(b.courseId || ""), topicCode = String(b.topicCode || "");
  const t = Object.prototype.hasOwnProperty.call(TOPICS, courseId + "|" + topicCode) ? TOPICS[courseId + "|" + topicCode] : null;
  if (!t) throw new BadInput("Unknown course or topic");
  return { courseId, topicCode, course: t.course, unitN: t.unitN, unitName: t.unitName, topicName: t.topicName, existing: t.stems };
}

function explainPrompt(c) {
  const L = "ABCD";
  return `A student is studying ${c.course}, CED Topic ${c.topicCode} "${c.topicName}".
${c.fig ? "The question has a figure described by this data: " + c.fig + "\n" : ""}Question: ${c.stem}
Options:
${c.options.map((o, i) => L[i] + ". " + o).join("\n")}
Correct answer: ${L[c.correct]}. The student chose: ${L[c.picked]}.

In 120 words or fewer of plain text with no markdown, explain why the correct answer is right${c.picked !== c.correct ? " and why the student's choice is wrong" : ""}. Then give one quick tip for remembering the concept on the AP exam.`;
}

function generatePrompt(c) {
  return `You write practice questions for ${c.course}, Unit ${c.unitN} (${c.unitName}), CED Topic ${c.topicCode}: "${c.topicName}".
Write 5 NEW, original, accurate AP-style multiple-choice questions for this topic only. Mix recall with application or data/scenario reasoning, at real AP exam difficulty. Each has exactly one correct answer and exactly 3 plausible wrong answers that reflect common misconceptions. Do not use "all of the above" or "none of the above". Give a 1-2 sentence explanation of why the correct answer is right. Do not repeat these existing questions:
${c.existing.map(x => "- " + x).join("\n")}`;
}
